# Generated by Django 4.2.3 on 2023-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0004_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
