# Generated by Django 4.2.3 on 2023-09-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0005_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='ph_no',
            new_name='phone_number',
        ),
    ]
