# Generated by Django 4.2.3 on 2023-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0005_sub_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
