# Generated by Django 4.2.3 on 2023-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0006_rename_full_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='products')),
                ('category_offer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_offer', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
