# Generated by Django 4.2.3 on 2023-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0006_product_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
