# Generated by Django 4.2.3 on 2023-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0008_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
