# Generated by Django 4.2.3 on 2023-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0008_remove_category_is_active_alter_category_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
