# Generated by Django 4.2.3 on 2023-09-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0010_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_offer',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_offer_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='Sub_category_id',
        ),
    ]
