# Generated by Django 4.2.3 on 2023-09-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
