# Generated by Django 4.2.3 on 2023-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0013_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
