# Generated by Django 4.2.3 on 2023-09-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0015_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Sub_category',
        ),
    ]
