# Generated by Django 4.2.3 on 2023-09-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0017_remove_product_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
    ]
