# Generated by Django 4.2.3 on 2023-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0018_remove_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
