# Generated by Django 4.2.3 on 2023-10-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0024_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
