# Generated by Django 4.2.3 on 2023-10-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0030_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
    ]
