# Generated by Django 4.2.3 on 2023-10-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0031_remove_productvariation_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
