# Generated by Django 4.2.3 on 2023-10-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0033_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='Brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
