# Generated by Django 4.2.3 on 2023-10-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0042_remove_cart_variation_remove_orderitem_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'returned'), ('refunded', 'refunded'), ('on_hold', 'on_hold')], default='pending', max_length=100),
        ),
    ]
