# Generated by Django 4.2.3 on 2023-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0047_alter_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=100, null=True),
        ),
    ]
