# Generated by Django 4.2.3 on 2023-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandshe', '0048_alter_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
